on: push

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files
        uses: appleboy/scp-action@master
        with:
          host: 49.232.175.63
          username: ubuntu
          password: Agag1994720
          port: 22
          source: "."
          target: "/www/wwwroot/sonder"
          overwrite: true
